recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LfqXN0SAAAAANToC-DKNfTJA0HSRgzBLJC_glEt"
	privateKey = "6LfqXN0SAAAAANK39eWfNnzXxC7XDKStCGyFwup8"

	// Include the noscript tags in the generated captcha
	includeNoScript = true

    // Force language change. See this for more: http://code.google.com/p/recaptcha/issues/detail?id=133
    forceLanguageInURL = false
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}